<?php
namespace HansSchouten\LaravelPageBuilder\Orig\Repositories;

use PHPageBuilder\Repositories\PageRepository as BasePageRepository;

class PageRepository extends BasePageRepository
{
    public function findWithId($id)
    {
        return parent::findWithId($id); // TODO: Change the autogenerated stub
    }
}