<?php


namespace HansSchouten\LaravelPageBuilder;



use PHPageBuilder\Modules\GrapesJS\Block\BaseController;
use PHPageBuilder\Modules\GrapesJS\Block\BaseModel;
use PHPageBuilder\Modules\GrapesJS\Block\BlockRenderer;
use PHPageBuilder\ThemeBlock;

class BlockRendererWrapper extends BlockRenderer
{
    /** @var ThemeWrapper */
    protected $theme;

    /**
     * @param ThemeBlock $themeBlock
     * @param null $blockData
     * @param null $id
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render(ThemeBlock $themeBlock, $blockData = null, $id = null)
    {
        return parent::render($themeBlock, $blockData, $id); // TODO: Change the autogenerated stub
    }


    /**
     * Overrides the function to return view file
     *
     * @param ThemeBlock $themeBlock
     * @param $blockData
     * @return \Illuminate\Contracts\View\View;
     */
    protected function renderDynamicBlock(ThemeBlock $themeBlock, $blockData)
    {
        $blockData = $blockData ?? [];
        $controller = new BaseController;
        $model = new BaseModel($themeBlock, $blockData, $this->page, $this->forPageBuilder);

        if ($themeBlock->getModelFile()) {
            require_once $themeBlock->getModelFile();
            $modelClass = $themeBlock->getModelClass();
            $model = new $modelClass($themeBlock, $blockData, $this->page, $this->forPageBuilder);
        }

        if ($themeBlock->getControllerFile()) {
            require_once $themeBlock->getControllerFile();
            $controllerClass = $themeBlock->getControllerClass();
            $controller = new $controllerClass;
        }
        $controller->init($model, $this->page, $this->forPageBuilder);
        $controller->handleRequest();

        // init additional variables that should be accessible in the view
        $vars = [
            'renderer' => $this,
            'page' => $this->page,
            'block' => $model,
        ];
        $themeName = $this->theme->getThemeSlug();
        $slug = $themeBlock->getSlug();
        $viewPath = 'pagebuilder::' . $themeName . '.blocks.' . $slug . '.view';
        $html = view()->make($viewPath, $vars);
        return $html;
    }
}