<?php


namespace HansSchouten\LaravelPageBuilder;



use PHPageBuilder\Modules\GrapesJS\Block\BaseController;
use PHPageBuilder\Modules\GrapesJS\Block\BaseModel;
use PHPageBuilder\Modules\GrapesJS\Block\BlockRenderer;

class BlockRendererWrapper extends BlockRenderer
{
    /** @var ThemeWrapper */
    protected $theme;


    public function render($themeBlock, $blockData = null, $id = null)
    {
        return parent::render($themeBlock, $blockData, $id); // TODO: Change the autogenerated stub
    }

    /**
     * Overrides the function to return view file
     *
     * @param ThemeBlockWrapper $themeBlock
     * @param $blockData
     * @return \Illuminate\Contracts\View\View;
     */
    protected function renderDynamicBlock($themeBlock, $blockData)
    {
        $blockData = $blockData ?? [];
        $controller = new BaseController;
        $model = new BaseModel($themeBlock, $blockData, $this->page, $this->forPageBuilder);

        if ($themeBlock->getModelFile()) {
            require_once $themeBlock->getModelFile();
            $modelClass = $themeBlock->getModelClass();
            $model = new $modelClass($themeBlock, $blockData, $this->page, $this->forPageBuilder);
        }

        if ($themeBlock->getControllerFile()) {
            require_once $themeBlock->getControllerFile();
            $controllerClass = $themeBlock->getControllerClass();
            $controller = new $controllerClass;
        }
        $controller->init($model, $this->page, $this->forPageBuilder);
        $html = $controller->handleRequest();
        if($html){
            return $html;
        }
        // init additional variables that should be accessible in the view
        $vars = [
            'renderer' => $this,
            'page' => $this->page,
            'block' => $model,
            'forPageBuilder' => $this->forPageBuilder,
        ];
        $themeName = $this->theme->getThemeSlug();
        $slug = $themeBlock->getSlug();
        $viewPath = 'pagebuilder::' . $themeName . '.blocks.' . $slug;
        if($this->forPageBuilder){
            $viewPath .= '.builder_view';
        }
        else {
            $viewPath .= '.view';
        }
        $html = view()->make($viewPath, $vars);
        return $html;
    }


}