<?php
namespace HansSchouten\LaravelPageBuilder;
use PHPageBuilder\Page as BasePage;

class Page extends BasePage
{
    public function getRoute($locale = null)
    {
        return route('');
        return parent::getRoute($locale); // TODO: Change the autogenerated stub
    }
}